name: Git

on: pull_request

jobs:
  conventional_commits:
    name: Conventional Commits
    runs-on: ubuntu-latest

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v4.1.12
        with:
          configFile: .commitlintrc.json
